config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:show, :index]

  get 'topics/index'
  get 'topics/show'
  resources :comments
  devise_for :users, path: '', path_names: {
    sign_in: 'login', sign_up: 'register', sign_out: 'logout'
  }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  # get 'pages/home'
  get 'angular-items', to: 'portfolios#angular'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  includes Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular
    where(subtitle: 'Angular')
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }

  after_initialize :set_defaults

  def self.by_position
    order('position ASC')
  end

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '150')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'portfolio'
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    # 3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html {
          redirect_to portfolios_path,
          notice: 'Your portfolio item is now live'
        }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio_item }
      else
        format.html { render :edit }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end


  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    @portfolio_item = Portfolio.find(params[:id])

    @portfolio_item.destroy

    # redirect
    respond_to do |format|
      format.html {
        redirect_to portfolios_url, notice: 'Portfolio item was removed'
      }
    end
  end

  private
    def portfolio_params
      params.require(:portfolio).permit(
        :title, :subtitle, :body, technologies_attributes: [
          :name, :id, :_destroy
        ]
      )
    end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :subtitle %>
      <%= form.text_area :subtitle, class: "form-control" %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <%= form.label :body %>
      <%= form.text_area :body, class: "form-control" %>
    </div>
  </div>

  <hr/>
  <div class="col-md-12">
    <h2>Technologies Used:</h2>
    <div>
      <%= form.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>
      <div>
        <%= link_to_add_association 'Add Technology', form, :technologies %>
      </div>
    </div>

  <div class="form-group">
    <%= form.submit "Submit Portfolio Item", class: 'btn btn-primary btn-block' %>
  </div>
</div>
</div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="card" data-id="<%= portfolio_item.id %>">
  <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
  <p class="card-text">
    <span>
      <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %>
    </span>
    <%= portfolio_item.subtitle %>
  </p>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>
<%= link_to "Create New Item", new_portfolio_path %>

<% @angular_portfolio_items.each do |portfolio_item| %>

  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item) %>
  <%= link_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, data: {confirm: 'Are you sure?'} %>
  <!-- <a href="/portfolios/<%= portfolio_item %>/edit">Edit Two</a> -->
  <!-- <p><%= portfolio_item.title %></p> -->
<% end %>

app/views/portfolios/edit.html.erb
<div class="container">
  <h1>Edit this new Portfolio Item</h1>

  <%= render "form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container">
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item, class: "portfolio-form" %>
</div>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag @portfolio_item.main_image %>

    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>
      <hr/>
      <em><%= @portfolio_item.subtitle %></em>
      <p>
        <%= @portfolio_item.body %>
      </p>
      <hr/>
      <h2>Technologies Used:</h2>

      <% @portfolio_item.technologies.each do |t| %>
        <p> <%= t.name %> </p>
      <% end %>
      <% if logged_in?(:site_admin) %>
        <div class="col-md-12">
          <%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: 'btn btn-warning text-white' %>
        </div>
      <% end %>

      <hr />
    </div>
  </div>
</div>